/** Documentos de empresa */
export const CARATULA = "CARATULA";
export const DESCRIPCION = "DESCRIPCION";
export const RENUMERATIVA = "RENUMERATIVA";
export const ASCENSOS = "ASCENSOS";
export const HOSTIGAMIENTO = "HOSTIGAMIENTO";
export const CAPACITACION = "CAPACITACION";
export const CONCILIACION = "CONCILIACION";
export const ANEXOS = "ANEXOS";
